[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

# API Service
[[services]]
name = "learningapp-api"
source = "LearningApp"

[services.build]
buildCommand = "dotnet restore && dotnet publish -c Release -o out"
startCommand = "dotnet out/LearningApp.dll"

[services.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"

# Web Service  
[[services]]
name = "learningapp-web"
source = "LearningApp.Web"

[services.build]
buildCommand = "dotnet restore && dotnet publish -c Release -o out"
startCommand = "dotnet out/LearningApp.Web.dll"

[services.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"